from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
import json

from app.core.database import get_db
from app.core.response import success_response, error_response
from app.api.deps import get_optional_current_user
from app.models.user import User
from app.models.trip import Trip, ItineraryItem, Place, ChatMessage
from app.schemas.trip import ChatRequest
from app.services.ai_assistant import ai_assistant
from app.services.weather_service import weather_service

router = APIRouter(prefix="/assistant", tags=["AI Tourist Assistant"])

@router.post("/chat", response_model=None)
async def chat_with_assistant(
    req: ChatRequest,
    current_user: User = Depends(get_optional_current_user),
    db: Session = Depends(get_db)
):
    trip_context = {}
    if req.trip_id:
        trip = db.query(Trip).filter(Trip.id == req.trip_id).first()
        if trip:
            weather_data = await weather_service.get_weather(city=trip.destination)
            itin_items = db.query(ItineraryItem).filter(ItineraryItem.trip_id == trip.id).all()
            trip_context = {
                "trip_id": trip.id,
                "title": trip.title,
                "destination": trip.destination,
                "current_location": trip.current_location,
                "members_count": trip.members_count,
                "budget": trip.budget,
                "estimated_cost": trip.estimated_cost,
                "start_date": trip.start_date,
                "end_date": trip.end_date,
                "interests": json.loads(trip.interests or "[]"),
                "weather": weather_data,
                "itinerary_count": len(itin_items)
            }

    # Override/merge with any custom context supplied in request
    if req.context:
        trip_context.update(req.context)

    # Generate assistant answer
    response_data = ai_assistant.generate_response(
        user_message=req.message,
        trip_context=trip_context
    )

    # Save to chat history if trip_id exists
    if req.trip_id:
        # Save user message
        db.add(ChatMessage(
            trip_id=req.trip_id,
            user_id=current_user.id if current_user else None,
            role="user",
            content=req.message
        ))
        # Save assistant message
        db.add(ChatMessage(
            trip_id=req.trip_id,
            user_id=current_user.id if current_user else None,
            role="assistant",
            content=response_data["reply"],
            action_payload=json.dumps(response_data.get("suggested_actions", []))
        ))
        db.commit()

    return success_response(
        data=response_data,
        message="AI assistant response generated"
    )

@router.get("/history/{trip_id}", response_model=None)
def get_chat_history(trip_id: int, db: Session = Depends(get_db)):
    msgs = db.query(ChatMessage).filter(ChatMessage.trip_id == trip_id).order_by(ChatMessage.created_at).all()
    results = []
    for m in msgs:
        actions = []
        if m.action_payload:
            try:
                actions = json.loads(m.action_payload)
            except Exception:
                actions = []
        results.append({
            "id": m.id,
            "role": m.role,
            "content": m.content,
            "suggested_actions": actions,
            "created_at": m.created_at.isoformat()
        })
    return success_response(data=results, message="Chat history retrieved")

@router.post("/action/apply", response_model=None)
def apply_assistant_action(
    payload: dict,
    db: Session = Depends(get_db)
):
    """
    Executes a structured action proposal generated by the AI Tourist Assistant.
    """
    trip_id = payload.get("trip_id")
    action_type = payload.get("action_type")
    action_data = payload.get("payload", {})

    trip = db.query(Trip).filter(Trip.id == trip_id).first() if trip_id else None
    if not trip:
        return error_response(message="Trip not found", status_code=status.HTTP_404_NOT_FOUND)

    if action_type == "add_to_itinerary":
        place_name = action_data.get("place_name")
        day_num = action_data.get("day", 1)
        place = db.query(Place).filter(Place.name.ilike(f"%{place_name}%")).first() if place_name else None
        
        # Calculate current max sort order for that day
        existing_items = db.query(ItineraryItem).filter(ItineraryItem.trip_id == trip.id, ItineraryItem.day_number == day_num).all()
        new_sort = len(existing_items) + 1

        new_item = ItineraryItem(
            trip_id=trip.id,
            day_number=day_num,
            time_slot="02:30 PM" if new_sort > 2 else "10:30 AM",
            place_id=place.id if place else None,
            custom_title=place.name if place else place_name,
            activity_type="attraction" if place else "custom",
            duration_hours=place.estimated_visit_hours if place else 2.0,
            notes=f"Added via AI Assistant Proposal"
        )
        db.add(new_item)
        db.commit()
        return success_response(data={"item_id": new_item.id}, message=f"Added '{new_item.custom_title}' to Day {day_num} itinerary!")

    elif action_type == "reduce_budget":
        new_accom = action_data.get("accommodation_type", "Standard")
        new_food = action_data.get("food_tier", "Standard")
        trip.accommodation_type = new_accom
        trip.food_budget_tier = new_food
        db.commit()
        return success_response(data={"trip_id": trip.id}, message=f"Updated accommodation to {new_accom} and food tier to {new_food}!")

    return success_response(data={"status": "acknowledged"}, message="Assistant proposal recorded.")
